name: Build and Push Docker Image to ECR
 
on:
  push:
    branches:
      - main
 
permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::066653777072:role/github-actions-ecr-role
          aws-region: ap-south-1
 
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build Docker image
        run: |
          docker build -t backend-js .
 
      - name: Tag Docker image
        run: |
          docker tag backend-js:latest 066653777072.dkr.ecr.ap-south-1.amazonaws.com/backend-js:latest
 
      - name: Push Docker image to ECR
        run: |
          docker push 066653777072.dkr.ecr.ap-south-1.amazonaws.com/backend-js:latest